#mysql

version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: my_database
      MYSQL_USER: user_name
      MYSQL_PASSWORD: user_password

volumes:
  db_data:
